// src\app\core\models\event.model.ts

class EventModel {
  constructor(
    public gender: string,
    public title: string,
    public otherTitle: string,
    public forename: string,
    public surname: string,
    public otherNames: boolean,
    public otherForename: string,
    public otherSurname: string,
    public mothersMaiden: string,
    public birthDate : Date,
    public countryOfBirth : string,
    public townOfBirth : string,
    public nationality : string,
    public hasUKNINO : boolean,
    public NINO: string,
    public hasPassport: boolean,
    public passportNo: string,
    public passportCountry: string,
    public hasDrivingLicence: boolean,
    public drivingLicence: string,
    public licenceCountry: string,
    public ElectricitySupplierNumber: string,
    public NatEntCardNo: string,
    public IsNICAvailable : boolean,
    public NICNumber : string,
    public NICCountryOfIssue : string,
    public PVGSchemeID : string,
    public EmailAddress : string,
    public EveningPhoneNumber : string,
    public DaytimePhoneNumber : string,
    public currResidentFrom : Date,
    public currAddrLine1 : string,
    public currAddrLine2 : string,
    public currAddrTown : string,
    public currAddrCounty : string,
    public currAddrPostCode : string,
    public currAddrCountry : string,
    public otherDetails : string,
    public userId: string,
    public _id?: string // _id is present if editing or returning from DB
  ) { }
}

class FormEventModel {
  constructor(
    public gender: string,
    public title: string,
    public otherTitle: string,
    public forename: string,
    public surname: string,
    public otherNames: boolean,
    public otherForename: string,
    public otherSurname: string,
    public mothersMaiden: string,
    public birthDate : string,
    public countryOfBirth : string,
    public townOfBirth : string,
    public nationality : string,   
    public hasUKNINO : boolean,
    public NINO: string,
    public hasPassport: boolean,
    public passportNo: string,
    public passportCountry: string,
    public hasDrivingLicence: boolean,
    public drivingLicence: string,
    public licenceCountry: string,
    public ElectricitySupplierNumber: string,
    public NatEntCardNo: string,
    public IsNICAvailable : boolean,
    public NICNumber : string,
    public NICCountryOfIssue : string,
    public PVGSchemeID : string,
    public EmailAddress : string,
    public EveningPhoneNumber : string,
    public DaytimePhoneNumber : string,
    public currResidentFrom : string,
    public currAddrLine1 : string,
    public currAddrLine2 : string,
    public currAddrTown : string,
    public currAddrCounty : string,
    public currAddrPostCode : string,
    public currAddrCountry : string,
    public otherDetails : string,
    public userId: string   

  ) { }
}

export { EventModel, FormEventModel };
